# yaml 配置实例
version: '3'
services:
  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    privileged: true
    networks:
      - webnet
  redis:
    image: "redis:6.2.5"
    ports:
      - "6379:6379"
    volumes:
      - "./redis/data:/data/redis/data"
      - "./redis/redis.conf:/etc/redis.conf"
    command: "redis-server /etc/redis.conf"
    restart: always
    privileged: true
    networks:
      - webnet
  nginx:
    image: "nginx:1.14.0"
    ports:
      - "8081:8081"
      - "8082:8082"
    restart: always
    privileged: true
    networks:
      - webnet
    volumes:
      - "../src/main/resources/static/www/:/www/"
      - "../src/main/resources/static/admin/:/www/admin/"
      - "../src/main/resources/static/js/:/www/js/"
      - "../src/main/resources/static/layui/:/www/layui/"
      - "./nginx/vhost:/etc/nginx/conf.d"
      - "./nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
  wework:
#    build: ./java
    image: daocloud.io/library/java
    restart: always
    privileged: true
    ports:
      - "8080:8080"
    networks:
      - webnet
    volumes:
      - "../lib/WeWorkFinanceSdk.so:/usr/lib/WeWorkFinanceSdk.so"
      - "../target/wework-msgaudit-3.0.jar:/var/run/wework-msgaudit-3.0.jar"
    command: "java -jar /var/run/wework-msgaudit-3.0.jar"
networks:
  webnet:
    driver: bridge
