server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      schema-locations: "classpath:db/schema.sql"
      data-locations: "classpath:db/data.sql"
      encoding: "utf-8"
      mode: ALWAYS


  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 192.168.1.168
    port: 6379
    #password: 123456
    timeout: 0 # 连接超时时间（毫秒）
    pool:
      max-active: -1 # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle: 0 # 连接池中的最小空闲连接
