server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
  sql:
    init:
      schema-locations: "classpath:db/schema.sql"
      data-locations: "classpath:db/data.sql"
      encoding: "utf-8"
      mode: ALWAYS

